In [44]:
# import cell
import nltk
from nltk.corpus import stopwords
import re
import pandas as pd
import pickle


In [39]:
# conda info --env

# conda environments:
#
base                  *  C:\Users\paten\anaconda3
my-rdkit-env             C:\Users\paten\anaconda3\envs\my-rdkit-env
py37                     C:\Users\paten\anaconda3\envs\py37


Note: you may need to restart the kernel to use updated packages.


In [40]:
# 유사도 확인 함수
import numpy as np

def most_similar(doc_id,similarity_matrix,matrix):
    print (f'Document: {documents_df.iloc[doc_id]["documents"]}')
    print ('\n')
    print ('Similar Documents:')
    if matrix=='Cosine Similarity':
        similar_ix=np.argsort(similarity_matrix[doc_id])[::-1]
    elif matrix=='Euclidean Distance':
        similar_ix=np.argsort(similarity_matrix[doc_id])
    for ix in similar_ix:
        if ix==doc_id:
            continue
        print('\n')
        print (f'Document: {documents_df.iloc[ix]["documents"]}')
        print (f'{matrix} : {similarity_matrix[doc_id][ix]}')

In [45]:
# Load documents 

# Drug bank complete slim data
drugbank_approved_df = pd.read_csv('D:/WorkSpace/master_thesis/Drug_Bank/result/drugbank_approved.tsv', sep='\t')
drugName = drugbank_approved_df['name']

# Drugbank vocabulary data
drugbank_voca_df = pd.read_csv('D:/WorkSpace/master_thesis/Drug_Bank/drugbank_vocabulary.csv')

# documents data (title, abstracts)
with open('D:/WorkSpace/master_thesis/data_pubmed/documents/approved_documents.pkl', 'rb') as f:
    documents = pickle.load(f)


In [51]:
print('Approved Drug: {}'.format(len(drugbank_approved_df)))
# len(drugbank_voca_df)
print('number of scraped Documents: {}'.format(len(documents)))

Approved Drug: 4270
number of scraped Documents: 4027


In [78]:
# convert from dictionary to data_frame 
documents_df = pd.DataFrame(list(documents.items()), columns=['drugName', 'documents'])


# Documents 소문자 변환
for i in range(len(documents_df)):
    documents_df.documents[i] = df_documents.documents[i].lower()


# Remove stopwords from nltk
stop_words_l = stopwords.words('english')
documents_df['documents_cleaned'] = documents_df.documents.apply(lambda x: " ".join(re.sub(r'[^a-zA-Z]',' ',w).lower() for w in x.split() if re.sub(r'[^a-zA-Z]',' ',w).lower() not in stop_words_l) )

In [79]:
# using base BERT
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

document_embeddings = sbert_model.encode(documents_df['documents_cleaned'])



In [ ]:
biobert_model = SentenceTransformer('')

In [81]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

pairwise_similarities=cosine_similarity(document_embeddings)
pairwise_differences=euclidean_distances(document_embeddings)

most_similar(0,pairwise_similarities,'Cosine Similarity')
most_similar(0,pairwise_differences,'Euclidean Distance')

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity 


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity : -0.021146124228835106


Document:   
Cosine Similarity

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Document: changing wheat bran structural properties by extrusion-cooking on a pilot and industrial scale: a comparative study. combination of extrusion and fermentation with  influence of durum wheat bran particle size on phytochemical content and on leavened bread baking quality. immunomodulatory effects of wheat bran arabinoxylan on raw264.7 macrophages via the nf-κb signaling pathway using rna-seq analysis. fortification of yellow alkaline noodles with wheat bran and the impact on physical and sensorial properties. a wheat bran inducible expression system for the efficient production of α-l-arabinofuranosidase in bacillus subtilis. conversion of wheat bran to xylanases and dye adsorbent by  efficiency of twin-screw extrusion of biodegradable poly (butylene succinate)-wheat bran blend. effects of different solid-state fermentation ratios of s. cerevisiae and l. plantarum on physico-chemical properties of wheat bran and the quality of whole wheat bread. digestibility, lactation perfor



Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document

Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document:   
Euclidean Distance : 22.670719146728516


Document: 

In [36]:
len(documents)
# documents_df

6

In [31]:
# pairwise_similarities
# document_embeddings
pairwise_similarities_test = cosine_similarity(document_embeddings)
print(pairwise_similarities_test)
print()
print(pairwise_similarities)

[[1.0000001  0.8365411  0.61181045 0.4764783  0.6589275  0.81594574]
 [0.8365411  1.         0.67819023 0.5372207  0.7253677  0.78296375]
 [0.61181045 0.67819023 0.99999994 0.6800262  0.6249758  0.71018046]
 [0.4764783  0.5372207  0.6800262  1.0000001  0.5375689  0.6229849 ]
 [0.6589275  0.7253677  0.6249758  0.5375689  1.0000002  0.78826356]
 [0.81594574 0.78296375 0.71018046 0.6229849  0.78826356 0.99999994]]

[[1.0000001  0.8365411  0.61181045 0.4764783  0.6589275  0.81594574]
 [0.8365411  1.         0.67819023 0.5372207  0.7253677  0.78296375]
 [0.61181045 0.67819023 0.99999994 0.6800262  0.6249758  0.71018046]
 [0.4764783  0.5372207  0.6800262  1.0000001  0.5375689  0.6229849 ]
 [0.6589275  0.7253677  0.6249758  0.5375689  1.0000002  0.78826356]
 [0.81594574 0.78296375 0.71018046 0.6229849  0.78826356 0.99999994]]


In [3]:
import gensim
import sklearn
import nltk # 영어 자연어 처리
from nltk import RegexpTokenizer
from nltk.corpus import stopwords
import numpy as np
import torch

print('gensim  version = {}'.format(gensim.__version__))
print('pytorch version = {}'.format(torch.__version__))
print('sklearn version = {}'.format(sklearn.__version__))
print('nltk  version = {}'.format(nltk.__version__))

gensim  version = 3.8.3
pytorch version = 1.7.1
sklearn version = 0.23.1
nltk  version = 3.5


In [2]:
# load pickle data
import pickle
import pandas as pd


# Drug bank complete slim data
drugbank_approved_df = pd.read_csv('D:/WorkSpace/master_thesis/Drug_Bank/result/drugbank_approved.tsv', sep='\t')
drugName = drugbank_approved_df['name']

# Drugbank vocabulary data
drugbank_voca_df = pd.read_csv('D:/WorkSpace/master_thesis/Drug_Bank/drugbank_vocabulary.csv')

# documents data (title, abstracts)
with open('D:/WorkSpace/master_thesis/data_pubmed/documents/approved_documents.pkl', 'rb') as f:
    documents = pickle.load(f)

In [114]:
# # drugbank_approved_df.name # column 명을 속성으로 접근
# # drugbank_approved_df.loc[0] # index명으로 접근

# # drug name으로 index 지정: set_index /reset_index
# test_df = drugbank_approved_df.set_index('name')
# # drugbank_approved_df.loc[0]
# print(test_df.loc['Lepirudin'])
# print()
# print(drugbank_approved_df.loc[0])

파이썬 데이터프레임 접근 방법
https://m.blog.naver.com/PostView.nhn?blogId=rian4u&logNo=221399141190&proxyReferer=https:%2F%2Fwww.google.com%2F

In [3]:
drugbank_approved_df.head()

drugbank_id                 name     type                    groups  \
0     DB00001            Lepirudin  biotech                  approved   
1     DB00002            Cetuximab  biotech                  approved   
2     DB00003         Dornase alfa  biotech                  approved   
3     DB00004  Denileukin diftitox  biotech  approved|investigational   
4     DB00005           Etanercept  biotech  approved|investigational   

  atc_codes                                            targets  \
0   B01AE02                                        Prothrombin   
1   L01XC06  Epidermal growth factor receptor|Low affinity ...   
2   R05CB13                                                DNA   
3   L01XX29  Interleukin-2 receptor subunit alpha|Interleuk...   
4   L04AB01  Tumor necrosis factor|High affinity immunoglob...   

                                          categories inchikey inchi  \
0  Amino Acids, Peptides, and Proteins|Anticoagul...      NaN   NaN   
1  Amino Acids, Peptides, and Proteins|Antibodies...      NaN   NaN   
2  Amino Acids, Peptides, and Proteins|Cough and ...      NaN   NaN   
3  ADP Ribose Transferases|Amino Acids, Peptides,...      NaN   NaN   
4  Agents reducing cytokine levels|Amino Acids, P...      NaN   NaN   

                                         description  
0  Lepirudin is identical to natural hirudin exce...  
1  Cetuximab is an epidermal growth factor recept...  
2  Dornase alfa is a biosynthetic form of human d...  
3  A recombinant DNA-derived cytotoxic protein co...  
4  Dimeric fusion protein consisting of the extra...

In [7]:
# input data 결정
print(len(drugbank_approved_df))
print(len(documents))

doc_list = documents.keys()
print(doc_list)

4270
4027
dict_keys(['Lepirudin', 'Cetuximab', 'Dornase alfa', 'Denileukin diftitox', 'Etanercept', 'Bivalirudin', 'Leuprolide', 'Peginterferon alfa-2a', 'Alteplase', 'Sermorelin', 'Interferon alfa-n1', 'Darbepoetin alfa', 'Urokinase', 'Goserelin', 'Reteplase', 'Erythropoietin', 'Salmon calcitonin', 'Interferon alfa-n3', 'Pegfilgrastim', 'Sargramostim', 'Peginterferon alfa-2b', 'Asparaginase Escherichia coli', 'Thyrotropin alfa', 'Antihemophilic factor, human recombinant', 'Anakinra', 'Gramicidin D', 'Human immunoglobulin G', 'Anistreplase', 'Insulin human', 'Tenecteplase', 'Menotropins', 'Interferon gamma-1b', 'Interferon alfa-2a, Recombinant', 'Desmopressin', 'Coagulation factor VIIa Recombinant Human', 'Oprelvekin', 'Palifermin', 'Glucagon', 'Aldesleukin', 'Botulinum Toxin Type B', 'Omalizumab', 'Lutropin alfa', 'Lyme disease vaccine (recombinant OspA)', 'Insulin lispro', 'Insulin glargine', 'Collagenase clostridium histolyticum', 'Rasburicase', 'Cetrorelix', 'Adalimumab', 'Somatotr

* 전처리 파트 =========================================================================================

In [12]:
# 소문자 통일
for key in documents.keys():
    documents[key] = documents[key].lower()


In [172]:
# 의약품 용어 통일 - 단어내 띄어쓰기 처리
# 결과에 크게 영향을 미치지 않을 것으로 예상하고 일단 SKip
# documents['Dornase alfa'] = documents['Dornase alfa'].replace('dornase alfa', 'dornase-alfa')

    

In [3]:
# 최초 1회 수행
# import nltk
# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\paten\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
# Remove stopwords
from nltk.corpus import stopwords

# stopwords for english
listStopWords = stopwords.words('english') 




In [68]:
# Tokenize (소문자로 통합)
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer  
from nltk.tokenize import TreebankWordTokenizer
# token_Dornasealf = word_tokenize(doc_Dornasealf)
# token_Lepirudin = word_tokenize(doc_Lepirudin)
# toekn_Ximelagatr = word_tokenize(doc_Ximelagatr)

# token_Dornasealf = WordPunctTokenizer().tokenize(doc_Dornasealf)
# token_Lepirudin = WordPunctTokenizer().tokenize(doc_Lepirudin)
# toekn_Ximelagatr = WordPunctTokenizer().tokenize(doc_Ximelagatr)


tokenizer = TreebankWordTokenizer()
token_doc = dict()
for key in documents.keys():
     token_doc[key] = tokenizer.tokenize(documents[key])

# token_Dornasealf = tokenizer.tokenize(doc_Dornasealf)
# token_Lepirudin = tokenizer.tokenize(doc_Lepirudin)
# toekn_Ximelagatr = tokenizer.tokenize(doc_Ximelagatr)

In [89]:
# token_doc =  [token_Dornasealf, token_Lepirudin, toekn_Ximelagatr]
#Stopwords 제거
token_wo_stopword = dict()
token_wo_stopword_list = [[word for word in token_doc[key] if not word in listStopWords] for key in token_doc.keys()]

drug_keys = token_doc.keys()
for i, key in enumerate(drug_keys):
    token_wo_stopword[key] = token_wo_stopword_list[i]
    


In [99]:
# Stemming(어간 추출)
from nltk.stem import PorterStemmer

pst = PorterStemmer()
token_stemmed = [[pst.stem(word) for word in token_wo_stopword[key]] for key in token_wo_stopword.keys()]

drug_keys = token_wo_stopword.keys()
token_result = dict()
for i, key in enumerate(drug_keys):
    token_result[key] = token_stemmed[i]


* 전처리 파트 =========================================================================================

In [19]:
from sklearn.cluster import KMeans
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

texts_and_tags = [
    (documents[key], [key]) for key in documents.keys()
]

TRAIN_documents = [TaggedDocument(words=text, tags=tags) for text, tags in texts_and_tags]


In [22]:
import time

start_time = time.time()

# Doc2Vec Training
model = Doc2Vec(TRAIN_documents, vector_size=5, window=3, epochs=40, min_count=0, workers=4)

print("running time: ", time.time() - start_time)
model.save('doc2vec_approved.model')

running time:  267.9928960800171


In [23]:
model.docvecs.most_similar('Lepirudin')

[('Eteplirsen', 0.9998279809951782),
 ('Everolimus', 0.999125063419342),
 ('Felis catus skin', 0.9987452626228333),
 ('Icosapent ethyl', 0.9983333945274353),
 ('Citicoline', 0.997514545917511),
 ('Dactinomycin', 0.9970820546150208),
 ('Levobunolol', 0.997021496295929),
 ('Avelumab', 0.9969208240509033),
 ('Netupitant', 0.9966803789138794),
 ('Tobramycin', 0.9965447187423706)]

In [33]:
from scipy import spatial

dor_lepi = spatial.distance.cosine(model.docvecs['Dornase alfa'], model.docvecs['Lepirudin'])
dor_xime = spatial.distance.cosine(model.docvecs['Dornase alfa'], model.docvecs['Ximelagatran'])
lepi_xime = spatial.distance.cosine(model.docvecs['Lepirudin'], model.docvecs['Ximelagatran'])

print('Dornase_Lepirudin: ', dor_lepi)
print('Dornase_Ximelagatran: ', dor_xime)
print('Lepirudin_Ximelagatran: ', lepi_xime)

Dornase_Lepirudin:  0.03801298141479492
Dornase_Ximelagatran:  1.1024495959281921
Lepirudin_Ximelagatran:  0.9245570600032806


In [56]:
lepirudin_abstracts = documents['Lepirudin']

doc_vec = model.infer_vector(lepirudin_abstracts.lower().split(" "))

# word2vec
print("== word similarity")
print(model.wv.similar_by_vector(doc_vec))

# doc2vec
print("== document similarity")
doc_sim_list = model.docvecs.most_similar(positive=[doc_vec], topn=len(model.docvecs))
for doc_id, sim in doc_sim_list:
    print(f"Document {doc_id} - similarity: {sim:.5f}")

print("== complete")

== word similarity
[('﹤', 0.8980783224105835), ('･', 0.8068166971206665), ('⟶', 0.8016313910484314), ('̂', 0.7972032427787781), ('ⅹ', 0.7858506441116333), ('Ρ', 0.7693530321121216), ('͘', 0.7562497854232788), ('ű', 0.7532801032066345), ('·', 0.7370501160621643), ('w', 0.7352657318115234)]
== document similarity
Document (2S)-2-(1H-indol-3-yl)pentanoic acid - similarity: 0.98621
Document Benorilate - similarity: 0.98586
Document Maclura tricuspidata whole - similarity: 0.98072
Document (5Z)-12-CHLORO-13,15-DIHYDROXY-4,7,8,9-TETRAHYDRO-2-BENZOXACYCLOTRIDECINE-1,10(3H,11H)-DIONE - similarity: 0.98010
Document N-((1R,2S)-2-(5-CHLORO-1H-INDOLE-2-CARBOXAMIDO)CYCLOHEXYL)-5-METHYL-4,5,6,7-TETRAHYDROTHIAZOLO[5,4-C]PYRIDINE-2-CARBOXAMIDE - similarity: 0.97496
Document 5-(HEXAHYDRO-2-OXO-1H-THIENO[3,4-D]IMIDAZOL-6-YL)PENTANAL - similarity: 0.97391
Document Caprylic alcohol - similarity: 0.97388
Document 1-[2-DEOXYRIBOFURANOSYL]-2,4-DIFLUORO-5-METHYL-BENZENE-5'MONOPHOSPHATE - similarity: 0.96908
D

Document Lintuzumab - similarity: 0.77979
Document SLV319 - similarity: 0.77975
Document Albaconazole - similarity: 0.77946
Document +/-METHYL 4-(AMINOIMINOMETHYL)-BETA-[3- INH (AMINOIMINO)PHENYL]BENZENE PENTANOATE - similarity: 0.77932
Document Lebrikizumab - similarity: 0.77931
Document Amineptine - similarity: 0.77892
Document 1,3-bis-([3-[3-[3-(4-{3-[3-nitro-5-(galactopyranosyloxy)-benzoylamino]-propyl}-piperazin-1-yl)-propylamino-3,4-dioxo-cyclobutenyl]-amino-propoxy-ethoxy-ethoxy]-propyl-]amino-carbonyloxy)-2-amino-propane - similarity: 0.77874
Document Magnesium levulinate - similarity: 0.77860
Document Dicoria canescens pollen - similarity: 0.77836
Document 4-{5-[(Z)-(2-IMINO-4-OXO-1,3-THIAZOLIDIN-5-YLIDENE)METHYL]FURAN-2-YL}BENZENESULFONAMIDE - similarity: 0.77834
Document Netazepide - similarity: 0.77827
Document Belapectin - similarity: 0.77820
Document 5-(5-CHLORO-2-THIENYL)-N-{(3S)-1-[(1S)-1-METHYL-2-MORPHOLIN-4-YL-2-OXOETHYL]-2-OXOPYRROLIDIN-3-YL}-1H-1,2,4-TRIAZOLE-3-SULF

Document Pamiparib - similarity: 0.69966
Document 2'-(4-Dimethylaminophenyl)-5-(4-Methyl-1-Piperazinyl)-2,5'-Bi-Benzimidazole - similarity: 0.69963
Document Nalorphine - similarity: 0.69941
Document N-METHYL(5-(PYRIDIN-3-YL)FURAN-2-YL)METHANAMINE - similarity: 0.69937
Document Maxacalcitol - similarity: 0.69925
Document Cefpodoxime - similarity: 0.69907
Document Tandutinib - similarity: 0.69898
Document MBO7133 - similarity: 0.69897
Document Arbekacin - similarity: 0.69886
Document 5-{[(4-AMINO-3-CHLORO-5-FLUOROPHENYL)SULFONYL]AMINO}-1,3,4-THIADIAZOLE-2-SULFONAMIDE - similarity: 0.69882
Document Pinaverium - similarity: 0.69872
Document Edetate disodium anhydrous - similarity: 0.69871
Document Sorghum bicolor subsp. drummondii pollen - similarity: 0.69866
Document 1-(5-TERT-BUTYL-1,3,4-OXADIAZOL-2-YL)-2-(METHYLAMINO)ETHANONE - similarity: 0.69866
Document Poloxamer 188 - similarity: 0.69853
Document Eritoran - similarity: 0.69850
Document Mepolizumab - similarity: 0.69845
Document (5-(

Document Mirabegron - similarity: 0.64612
Document Influenza B virus B/Massachusetts/2/2012 recombinant hemagglutinin antigen - similarity: 0.64608
Document Triglyme - similarity: 0.64606
Document Calaspargase pegol - similarity: 0.64603
Document PR1 leukemia peptide vaccine - similarity: 0.64599
Document 2-Allylphenol - similarity: 0.64598
Document Epinastine - similarity: 0.64597
Document Cynodon dactylon pollen - similarity: 0.64594
Document Tepoxalin - similarity: 0.64593
Document Micronomicin - similarity: 0.64584
Document Fluvastatin - similarity: 0.64583
Document Annamycin - similarity: 0.64583
Document 3,6-DIAMINO-5-CYANO-4-(4-ETHOXYPHENYL)THIENO[2,3-B]PYRIDINE-2-CARBOXAMIDE - similarity: 0.64579
Document Tiletamine - similarity: 0.64579
Document Tigatuzumab - similarity: 0.64570
Document Streptococcus pneumoniae type 9v capsular polysaccharide antigen - similarity: 0.64556
Document Dopexamine - similarity: 0.64548
Document White mustard seed - similarity: 0.64547
Document 4,5-

Document Brazil nut - similarity: 0.59776
Document Doxercalciferol - similarity: 0.59775
Document Aminophenazone - similarity: 0.59771
Document Lomerizine - similarity: 0.59771
Document Gabapentin - similarity: 0.59770
Document TTP889 - similarity: 0.59764
Document Pentastarch - similarity: 0.59763
Document Luspatercept - similarity: 0.59759
Document Quetiapine - similarity: 0.59757
Document Mavacamten - similarity: 0.59753
Document Morus rubra pollen - similarity: 0.59747
Document Ampreloxetine - similarity: 0.59747
Document Proguanil - similarity: 0.59743
Document Ezetimibe - similarity: 0.59737
Document Calcium oxide - similarity: 0.59734
Document 2-ANILINO-6-CYCLOHEXYLMETHOXYPURINE - similarity: 0.59729
Document Diazepinomicin - similarity: 0.59726
Document Menthyl salicylate - similarity: 0.59723
Document Lornoxicam - similarity: 0.59720
Document LX1031 - similarity: 0.59720
Document Cinitapride - similarity: 0.59717
Document Lanosterol - similarity: 0.59716
Document Mitoxantrone 

Document (E)-(4S,6S)-6-((S)-2-{(S)-2-[(FURAN-2-CARBONYL)-AMINO]-3-METHYL-BUTYRYLAMINO}-3-METHYL-BUTYRYLAMINO)-8-METHYL-5-OXO-4-((R)-2-OXO-PYRROLIDIN-3-YLMETHYL)-NON-2-ENOIC ACID ETHYL ESTER - similarity: 0.55792
Document R667 - similarity: 0.55785
Document Margetuximab - similarity: 0.55785
Document Cephalothin Group - similarity: 0.55784
Document METHYL 3-CHLORO-2-{3-[(2,5-DIHYDROXY-4-METHOXYPHENYL)AMINO]-3-OXOPROPYL}-4,6-DIHYDROXYBENZOATE - similarity: 0.55779
Document 4-demethyl-4-cholesteryloxycarbonylpenclomedine - similarity: 0.55777
Document Influenza A virus A/Uruguay/716/2007(H3N2) hemagglutinin antigen (formaldehyde inactivated) - similarity: 0.55775
Document Cibacron Blue - similarity: 0.55772
Document beta-2-Thienyl-L-alanine - similarity: 0.55767
Document 1-tert-butyl-3-(3-methylbenzyl)-1H-pyrazolo[3,4-d]pyrimidin-4-amine - similarity: 0.55767
Document 2,6-DIMETHYL-1-(3-[3-METHYL-5-ISOXAZOLYL]-PROPANYL)-4-[2-METHYL-4-ISOXAZOLYL]-PHENOL - similarity: 0.55766
Document Lycope

Document Motolimod - similarity: 0.52049
Document Otamixaban - similarity: 0.52045
Document Angiotensin II - similarity: 0.52041
Document Dostarlimab - similarity: 0.52035
Document 2-(N-morpholino)ethanesulfonic acid - similarity: 0.52033
Document MK-0686 - similarity: 0.52027
Document Lanolin alcohols - similarity: 0.52026
Document Ambrosia acanthicarpa pollen - similarity: 0.52021
Document Polycarbophil - similarity: 0.52015
Document 1-Hydroxyamine-2-Isobutylmalonic Acid - similarity: 0.52013
Document Magnesium cation - similarity: 0.52012
Document 5-[(3S)-3-(2-methoxybiphenyl-4-yl)but-1-yn-1-yl]-6-methylpyrimidine-2,4-diamine - similarity: 0.52007
Document Phenolphthalein - similarity: 0.52006
Document Melarsoprol - similarity: 0.52005
Document Fructose-6-phosphate - similarity: 0.52003
Document Alvimopan - similarity: 0.52003
Document Nomacopan - similarity: 0.51992
Document Staurosporine - similarity: 0.51986
Document Nitroxoline - similarity: 0.51981
Document Balsalazide - simila

Document Vancomycin - similarity: 0.46221
Document Salsalate - similarity: 0.46221
Document (+)-Rutamarin alcohol - similarity: 0.46210
Document Asfotase alfa - similarity: 0.46210
Document CEP-9722 - similarity: 0.46202
Document Orbifloxacin - similarity: 0.46199
Document Calcium citrate - similarity: 0.46198
Document Lima bean - similarity: 0.46196
Document Neisseria meningitidis group y capsular polysaccharide diphtheria toxoid conjugate antigen - similarity: 0.46185
Document Edetic acid - similarity: 0.46180
Document Cypermethrin - similarity: 0.46178
Document Fenofibrate - similarity: 0.46177
Document Inosine pranobex - similarity: 0.46176
Document 5-[(2-AMINOETHYL)AMINO]-6-FLUORO-3-(1H-PYRROL-2-YL)BENZO[CD]INDOL-2(1H)-ONE - similarity: 0.46167
Document Riboprine - similarity: 0.46164
Document (2R)-3-{[(BENZYLAMINO)CARBONYL]AMINO}-2-HYDROXYPROPANOIC ACID - similarity: 0.46156
Document 1-BENZYL-4-[(5,6-DIMETHOXY-1-INDANON-2-YL)METHYL]PIPERIDINE - similarity: 0.46154
Document OPC-28

Document Ranimustine - similarity: 0.41489
Document ADX-10061 - similarity: 0.41488
Document Tioxolone - similarity: 0.41481
Document Potassium chloride - similarity: 0.41476
Document Carbonate ion - similarity: 0.41456
Document 11-MERCAPTOUNDECANOIC ACID - similarity: 0.41454
Document Unoprostone - similarity: 0.41445
Document Tirapazamine - similarity: 0.41443
Document PN0621 - similarity: 0.41436
Document N-(4-bromo-2-{[(3R,5S)-3,5-dimethylpiperidin-1-yl]carbonyl}phenyl)-4-morpholin-4-yl-4-oxobutanamide - similarity: 0.41425
Document 1,2-Dihydroxynaphthalene - similarity: 0.41401
Document Icatibant - similarity: 0.41401
Document Magnesium acetate - similarity: 0.41397
Document Cortisone acetate - similarity: 0.41382
Document Starch, corn - similarity: 0.41381
Document Mifamurtide - similarity: 0.41381
Document Warfarin - similarity: 0.41374
Document Influenza A virus A/Singapore/GP2050/2015 (H3N2) antigen (MDCK cell derived, propiolactone inactivated) - similarity: 0.41364
Document 

Document Bucillamine - similarity: 0.36084
Document 3-Methyl-5-Sulfo-Pyrrolidine-2-Carboxylic Acid - similarity: 0.36079
Document Matairesinol - similarity: 0.36077
Document Rutin - similarity: 0.36062
Document Abacavir hydroxyacetate - similarity: 0.36032
Document Choline C 11 - similarity: 0.36019
Document Fosmidomycin - similarity: 0.36018
Document Brivanib alaninate - similarity: 0.36016
Document Emricasan - similarity: 0.36014
Document Bucladesine - similarity: 0.36012
Document Proxyphylline - similarity: 0.36006
Document Valomaciclovir - similarity: 0.35996
Document ENMD-1198 - similarity: 0.35982
Document Beta-hydroxyfentanyl - similarity: 0.35981
Document N(G)-Iminoethylornithine - similarity: 0.35950
Document Adafosbuvir - similarity: 0.35948
Document Kinetin - similarity: 0.35938
Document INGN 201 - similarity: 0.35936
Document 5-monophosphate-9-beta-D-ribofuranosyl xanthine - similarity: 0.35924
Document L-threonic acid - similarity: 0.35917
Document Darinaparsin - similarit

Document L-Gluconic Acid - similarity: 0.28595
Document N,N-dimethylarginine - similarity: 0.28592
Document 2-Fluoroaniline - similarity: 0.28588
Document Lifitegrast - similarity: 0.28568
Document Phendimetrazine - similarity: 0.28542
Document CUDC-907 - similarity: 0.28540
Document Carob - similarity: 0.28540
Document (2Z)-N-biphenyl-4-yl-2-cyano-3-hydroxybut-2-enamide - similarity: 0.28537
Document Bifemelane - similarity: 0.28531
Document Epicriptine - similarity: 0.28508
Document Pelitinib - similarity: 0.28507
Document Ataluren - similarity: 0.28491
Document Cauliflower - similarity: 0.28475
Document Amdoxovir - similarity: 0.28475
Document Censavudine - similarity: 0.28457
Document Sinapultide - similarity: 0.28456
Document Hexoprenaline - similarity: 0.28453
Document Sophora flavescens root - similarity: 0.28451
Document Coltuximab ravtansine - similarity: 0.28444
Document 5-Mercaptoethanol-2-decenoyl-coenzyme A - similarity: 0.28435
Document 6-amino-4-(2-phenylethyl)-1,7-dihyd

Document 6-[(Z)-Amino(Imino)Methyl]-N-[4-(Aminomethyl)Phenyl]-4-(Pyrimidin-2-Ylamino)-2-Naphthamide - similarity: 0.20162
Document Tl-3-093 - similarity: 0.20149
Document Albuvirtide - similarity: 0.20141
Document (2Z)-3-{[Oxido(oxo)phosphoranyl]oxy}-2-phenylacrylate - similarity: 0.20117
Document Methylselenocysteine - similarity: 0.20115
Document Varicella Zoster Vaccine (Recombinant) - similarity: 0.20104
Document Ulodesine - similarity: 0.20092
Document (S)-2-[(R)-3-amino-4-(2-fluorophenyl)butyryl]-1,2,3,4-tetrahydroisoquinoline-3-carboxamide - similarity: 0.20085
Document Dihydroxymethoxychalcone - similarity: 0.20073
Document 4-(2-Thienyl)Butyric Acid - similarity: 0.20037
Document Risedronic acid - similarity: 0.20036
Document 1,3-diphenylurea - similarity: 0.20035
Document S,S-Propylthiocysteine - similarity: 0.20014
Document alpha,alpha-Dibromo-D-camphor - similarity: 0.19993
Document Biropepimut-S - similarity: 0.19992
Document DAS-181 - similarity: 0.19990
Document Epoetin d

Document 3-thiaoctanoyl-CoA - similarity: 0.10803
Document S-Isopropyl-Isothiourea - similarity: 0.10795
Document Zalifrelimab - similarity: 0.10773
Document 3-FLUORO-5-MORPHOLIN-4-YL-N-[3-(2-PYRIDIN-4-YLETHYL)-1H-INDOL-5-YL]BENZAMIDE - similarity: 0.10760
Document Furaprevir - similarity: 0.10734
Document N-(M-Trifluoromethylphenyl) Phenoxazine-4,6-Dicarboxylic Acid - similarity: 0.10732
Document Englitazone - similarity: 0.10725
Document Practolol - similarity: 0.10719
Document Polyquaternium-10 (400 cps at 2%) - similarity: 0.10712
Document N-acetyl-L-arginine - similarity: 0.10692
Document [2,4,6-Triisopropyl-Phenylsulfonyl-L-[3-Amidino-Phenylalanine]]-Piperazine-N'-Beta-Alanine - similarity: 0.10687
Document (1S)-1-AMINO-2-(1H-INDOL-3-YL)ETHANOL - similarity: 0.10683
Document beta-(1->4)-galactotriose - similarity: 0.10666
Document 3-nitro-L-tyrosine - similarity: 0.10665
Document Irdabisant - similarity: 0.10658
Document H TYPE II TRISACCHARIDE - similarity: 0.10653
Document UDP-

Document [N-(BENZYLOXYCARBONYL)AMINO](4-AMIDINOPHENYL)METHANE-PHOSPHONATE - similarity: -0.03256
Document Eltanolone - similarity: -0.03262
Document 3-{[(5R,6R)-5-Benzyl-6-hydroxy-2,4-bis(4-hydroxybenzyl)-3-oxo-1,2,4-triazepan-1-yl]sulfonyl}benzonitril - similarity: -0.03270
Document 1(R)-1-ACETAMIDO-2-(3-CARBOXY-2-HYDROXYPHENYL)ETHYL BORONIC ACID - similarity: -0.03286
Document Inhibitor BEA409 - similarity: -0.03293
Document N-Carbamoylphenylalanine - similarity: -0.03299
Document 1-(3-METHYLPHENYL)-1H-BENZIMIDAZOL-5-AMINE - similarity: -0.03315
Document R-30490 - similarity: -0.03333
Document 17alpha-Estriol - similarity: -0.03335
Document 2-({[2,3,5,6-TETRAFLUORO-3'-(TRIFLUOROMETHOXY)BIPHENYL-4-YL]AMINO}CARBONYL)CYCLOPENTA-1,3-DIENE-1-CARBOXYLIC ACID - similarity: -0.03361
Document CHF 4227 - similarity: -0.03386
Document Omoconazole - similarity: -0.03446
Document Odocoileus virginianus hair - similarity: -0.03452
Document L-erythro-7,8-dihydrobiopterin - similarity: -0.03456
Docu

Document (3R)-3-[3,5-Bis(trifluoromethyl)anilino]-2-cyano-3-sulfanylpropanamide - similarity: -0.44860
Document Heparin Disaccharide I-S - similarity: -0.44944
Document CGP 4832 - similarity: -0.44974
Document 1,3,4,9-Tetrahydro-2-(Hydroxybenzoyl)-9-[(4-Hydroxyphenyl)Methyl]-6-Methoxy-2h-Pyrido[3,4-B]Indole - similarity: -0.44983
Document 5-(4'-AMINO-1'-ETHYL-5',8'-DIFLUORO-1'H-SPIRO[PIPERIDINE-4,2'-QUINAZOLINE]-1-YLCARBONYL)PICOLINONITRILE - similarity: -0.45022
Document Trestolone acetate - similarity: -0.45203
Document 3h-Indole-5,6-Diol - similarity: -0.45475
Document Bimoclomol - similarity: -0.45507
Document (S)-oxalosuccinic acid - similarity: -0.45621
Document Guanosine 5'-diphosphate 2':3'-cyclic monophosphate - similarity: -0.45830
Document 2-Hexyloxy-6-Hydroxymethyl-Tetrahydro-Pyran-3,5-Diol - similarity: -0.45834
Document Tucotuzumab celmoleukin - similarity: -0.45918
Document 1-METHYL-5-(2-PHENOXYMETHYL-PYRROLIDINE-1-SULFONYL)-1H-INDOLE-2,3-DIONE - similarity: -0.45943
Doc

In [50]:
# trained_doc_vec = model.docvecs[tags[0]]
# inferred_doc_vec = model.infer_vector(text)
# print(texts_and_tags[0].tags)
# print(texts_and_tags[0][0])

# len(model.docvecs)
# model.docvecs.most_similar('Lepirudin')
# model.most_similar('and', topn=10)
from scipy import spatial

# vec1 = d2v_model.infer_vector(fisrt_text.split())
# vec2 = d2v_model.infer_vector(second_text.split())

# cos_distance = spatial.distance.cosine(vec1, vec2)

# score = model.n_similarity(questions1_split[i],questions2_split[i])
score = model.docvecs.similarity('Lepirudin', 'Ximelagatran')


# lep_xime_similarity = spatial.distance.cosine(model.docvecs['Lepirudin'], model.docvecs['Ximelagatran'])
# lep_nita_similarity = spatial.distance.cosine(model.docvecs['Lepirudin'], model.docvecs['Nitazoxanide'])
# print(lep_xime_similarity)
# print(lep_nita_similarity)

<ipython-input-50-e2d2d85d7922>:17: DeprecationWarning: Call to deprecated `similarity` (Method will be removed in 4.0.0, use self.wv.similarity() instead).
  score = model.similarity('Lepirudin', 'Ximelagatran')


KeyError: "word 'Lepirudin' not in vocabulary"

P01AX11 — Nitazoxanide
B01AE02 — Lepirudin
> similar 0.9988

B01AE02 — Lepirudin
B01AE05 — Ximelagatran

유사도 API
model.n_similarity()  
: 단어 리스트에 있는 모든 단어 벡터의 mean을 계산

 -> unit-normalzation -> cosine-similary 계산하기    

In [40]:
df_atc.head()

drugbank_id                 name     type                    groups  \
0     DB00001            Lepirudin  biotech                  approved   
1     DB00002            Cetuximab  biotech                  approved   
2     DB00003         Dornase alfa  biotech                  approved   
3     DB00004  Denileukin diftitox  biotech  approved|investigational   
4     DB00005           Etanercept  biotech  approved|investigational   

  atc_codes                                         categories inchikey inchi  \
0   B01AE02  Amino Acids, Peptides, and Proteins|Anticoagul...      NaN   NaN   
1   L01XC06  Amino Acids, Peptides, and Proteins|Antibodies...      NaN   NaN   
2   R05CB13  Amino Acids, Peptides, and Proteins|Cough and ...      NaN   NaN   
3   L01XX29  ADP Ribose Transferases|Amino Acids, Peptides,...      NaN   NaN   
4   L04AB01  Agents reducing cytokine levels|Amino Acids, P...      NaN   NaN   

                                         description  
0  Lepirudin is identical to natural hirudin exce...  
1  Cetuximab is an epidermal growth factor recept...  
2  Dornase alfa is a biosynthetic form of human d...  
3  A recombinant DNA-derived cytotoxic protein co...  
4  Dimeric fusion protein consisting of the extra...

In [14]:
# Accesing vector
doc_vec = dict()
cnt=0
for text, tags in texts_and_tags:
    cnt += 1
    trained_doc_vec = model.docvecs[tags[0]]
    inferred_doc_vec = model.infer_vector(text)
    doc_vec[tags[0]] = [trained_doc_vec, inferred_doc_vec]
    
#     print(f"tags: {tags}, text: {text}")
    print(f"tags: {tags}")
    print(f"trained_doc_vec: {trained_doc_vec}")
    print(f"inferred_doc_vec: {inferred_doc_vec}")
    print("--"*20)
    if(cnt == 3):
        break

TypeError: Parameter doc_words of infer_vector() must be a list of strings (not a single string).

In [181]:
# return_docs = model.docvecs.most_similar(positive=[inferred_vector],topn=5)
from scipy import spatial

dor_lepi = spatial.distance.cosine(doc_vec['Dornasealf'][1], doc_vec['Lepirudin'][1])
dor_xime = spatial.distance.cosine(doc_vec['Dornasealf'][1], doc_vec['Ximelagatr'][1])
lepi_xime = spatial.distance.cosine(doc_vec['Lepirudin'][1], doc_vec['Ximelagatr'][1])

print('dor_lepi: ', dor_lepi)
print('dor_xime: ', dor_xime)
print('lepi_xime: ', lepi_xime)
# for i in enumerate(doc_vec.keys()):
#     print(i)
#     spatial.distance.cosine(doc_vec[i][1], doc_vec[i+1][1])

dor_lepi:  0.5919299721717834
dor_xime:  0.5868140459060669
lepi_xime:  0.6061707735061646


In [171]:
# Document Clustering
print("##"*30)
print("K-Means Clustering")
print("##"*30)
Clustering_Method = KMeans(n_clusters=2, random_state=0)
X = model.docvecs.vectors_docs # document vector 전체를 가져옴. 
Clustering_Method.fit(X)# fitting 

cluster_dict = {i:[] for i in range(0, 2)}
for text_tags, label in zip(texts_and_tags, Clustering_Method.labels_):
    text, tags = text_tags
    cluster_dict[label].append(text)
for label, lst in cluster_dict.items():
    print(f"Cluster {label}")
    for x in lst:
        print(x)
    print("--"*30)
print("##"*20)

############################################################
K-Means Clustering
############################################################
Cluster 0
['[', '``', 'dornase-alfa', 'cystic', 'fibrosis.', 'dornase-alfa', 'current', 'use', 'mucolyt', 'treat', 'pulmonari', 'diseas', '(', 'major', 'caus', 'morbid', 'mortal', ')', 'cystic', 'fibrosis.', 'reduc', 'mucu', 'viscos', 'lung', ',', 'promot', 'improv', 'clearanc', 'secretions.', 'updat', 'previous', 'publish', 'review.', 'determin', 'whether', 'use', 'dornase-alfa', 'cystic', 'fibrosi', 'associ', 'improv', 'mortal', 'morbid', 'compar', 'placebo', 'medic', 'improv', 'airway', 'clearanc', ',', 'identifi', 'advers', 'event', 'associ', 'use.', 'search', 'cochran', 'cystic', 'fibrosi', 'genet', 'disord', 'group', 'trial', 'regist', 'compris', 'refer', 'identifi', 'comprehens', 'electron', 'databas', 'search', ',', 'handsearch', 'relev', 'journal', 'abstract', 'conferences.', 'date', 'recent', 'search', 'group', "'s", 'cystic', 'fibrosi',